[package]
name = "letmeout"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
hex = "0.4.3"
hmac = "0.12.1"
reqwest = { version = "0.12.8", features = ["json"] }
serde_json = "1.0.132"
sha2 = "0.10.8"
slack-morphism = "2.5.0"
